name: Download Mobox

on:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * *'

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Download installers
      run: |
        git clone https://gitlab.com/XTx9dAvTpjiN/mobox-private-packages.git
    - name: Release
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          cd gitlab-repo
          gh release create latest --title "mobox" --notes ""
